[icons]
TelegramDesktop = ""
firefox = ""
vlc = ""
Chromium-browser = ""
firefox-nightly = ""
Alacritty = ""
wezterm = ""
kitty = ""
Termite = ""
Thunderbird = ""
Gpick = ""
Nautilus = "📘"
Thunar = "📘"
Evince = ""
discord = ""
Pavucontrol = ""

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"
"org.wezfurlong.wezterm" = "wezterm"

[general]
wm_property = "class"

[options]
remove_duplicates = true
no_names = false
no_icon_names = true
